// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS8z2BKVHMOLudEssUBC68GK05R2ucVYc',
    appId: '1:211690327785:web:1ca78ae15f8cce2238ea78',
    messagingSenderId: '211690327785',
    projectId: 'odigan-d3cf8',
    authDomain: 'odigan-d3cf8.firebaseapp.com',
    storageBucket: 'odigan-d3cf8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCCiHur_d6bsfK47zbh0s7yTudH5Lyelo',
    appId: '1:211690327785:android:f8adfd7195317de638ea78',
    messagingSenderId: '211690327785',
    projectId: 'odigan-d3cf8',
    storageBucket: 'odigan-d3cf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqjH1Zg6_abTu9nUOL6KehqY3DBU-vIJ4',
    appId: '1:211690327785:ios:7d915efd140351fb38ea78',
    messagingSenderId: '211690327785',
    projectId: 'odigan-d3cf8',
    storageBucket: 'odigan-d3cf8.appspot.com',
    androidClientId: '211690327785-6qbfjsg0liu4md22ivn3l9rq8g4e3s65.apps.googleusercontent.com',
    iosClientId: '211690327785-0pqdodihhqikjgu3o3qtehriphfije17.apps.googleusercontent.com',
    iosBundleId: 'com.example.odigan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqjH1Zg6_abTu9nUOL6KehqY3DBU-vIJ4',
    appId: '1:211690327785:ios:7d915efd140351fb38ea78',
    messagingSenderId: '211690327785',
    projectId: 'odigan-d3cf8',
    storageBucket: 'odigan-d3cf8.appspot.com',
    androidClientId: '211690327785-6qbfjsg0liu4md22ivn3l9rq8g4e3s65.apps.googleusercontent.com',
    iosClientId: '211690327785-0pqdodihhqikjgu3o3qtehriphfije17.apps.googleusercontent.com',
    iosBundleId: 'com.example.odigan',
  );
}
